version: "3.9"
services:
  discovery:
    build: ../../discovery-server
    ports:
      - "8761:8761"
    image: "discovery-service"
  config:
    build: ../../config-server
    ports:
      - "8888:8888"
    image: "config-service" 
  vendeur_B:
    build: ../../vendeursMS
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "3000:8085"
    image: "docker-service-vendeurs"
  lunettes_B:
    build: ../../lunettesMS
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "3001:8086"
    image: "docker-service-lunettes"
    

