version: "3.9"
services:
  discovery:
    build: ../../discovery-server
    ports:
      - "8761:8761"
    image: "discovery-service"
  vendeur_B:
    build: ../../vendeursMS
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.cloud.config.uri=http://config:8888
    ports:
      - "3000:8085"
    image: "docker-service-vendeurs"
  lunettes_B:
    build: ../../lunettesMS
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.cloud.config.uri=http://config:8888
    ports:
      - "3001:8086"
    image: "docker-service-lunettes"
  clients_B:
    build: ../../clientsMS
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "3002:8083"
    image: "docker-service-clients"
  config:
    build: ../../config-server
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    volumes:
      - type: bind
        source: ./src/main/resources/centralRepo
        target: /config
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.profiles.active=native
    ports:
      - "8888:8888"
    image: "config-server"
  gateway:
    build: ../../zuul-server
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8762:8762"
    image: "gateway-server" 
    

